feeds/urls.py
from django.urls import path, include
from feeds import views as views


urlpatterns = [
    path("api/", include(('feeds.api_urls', 'feeds_api'), namespace='api')),
    path("feed/<str:tagName>/", views.tag_feed, name='tag_feed'),
    path("", views.front_feed, name='front_feed'),
]

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as dviews
import users.views as views

urlpatterns = [
    path('login/', dviews.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.registration, name='register'),
    path('register_tag/', views.register_tag, name='register_tag'),
    path('forgotpass/', views.forgotpass, name='forgotpass'),
    path('reset-password/<str:key>/', views.resetpass, name='resetpass'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path("api/", include(('users.api_urls', 'users_api'), namespace='api')),

]

werubin/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

# swagger import
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from werubin.generators import BothHttpAndHttpsSchemaGenerator


api_urlpatterns = [
    path('', include(('feeds.urls', 'feeds'), namespace='feeds')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
]
schema_view = get_schema_view(
    openapi.Info(
        title="WERUBIN API Documentation",
        default_version='v1',
        description="🙌 READ ME !!! 🙌 \n In this swagger, you will find all the api endpoint that we provide you. \n\
        This api allows you to interact in any way (except to registering process) with the content of our website \
        in case you want to build an app on top of ours.\
        Note that in order to user the api, you need to be registered on our website. \n \
        We are using Basic Authentication so you can either add the authorization header with your username and password encoded in Base64 separated by a column (:) \
        or if you are using curl, the -u option should work just fine.",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    patterns=api_urlpatterns,
    public=True,
    generator_class=BothHttpAndHttpsSchemaGenerator,
    permission_classes=[permissions.IsAuthenticated],
)
urlpatterns = api_urlpatterns + [

    path('travels/', include(('travels.urls', 'travels'), namespace='travels')),
    path("users/", include(("users.urls", "users"), namespace="users")),
    path('admin/', admin.site.urls),
    # json and yaml version
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    # 2 different UI of swagger
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    # background image in css file
    path('css/users.css', TemplateView.as_view(
        template_name='users.css',
        content_type='text/css')
    ),
    path('js/addToAlbumModal.js', TemplateView.as_view(
        template_name='addToAlbumModal.js',
        content_type='text/javascript')
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # add media url to urlpatterns

travels/models.py
from django.db import models
# https://stackoverflow.com/questions/15285740/make-django-admin-to-display-no-more-than-100-characters-in-list-results
from django.template.defaultfilters import truncatechars  # or truncatewords
import datetime
from django.utils import timezone


class Post(models.Model):
    """
        A Post:
            - is created by a User
            - contains a text content
            - can contain images (the image are a separate models named PostImages each pointing to a post)
            - might be in multiple Albums or none
            - can be shared
            - can be commented
            - can be liked
            - has a location
            - has tags
    """
    MAX_LENGTH = 300
    content = models.TextField("Text content", blank=True, null=True)
    creation_date = models.DateTimeField("creation date", auto_now=False, auto_now_add=True)
    last_edited = models.DateTimeField("Last edit", auto_now=True, auto_now_add=False)
    author = models.ForeignKey("users.User", verbose_name="User", on_delete=models.CASCADE, related_name="author")
    shares = models.ForeignKey("Post", verbose_name="Shared post", on_delete=models.CASCADE, null=True, blank=True)  # for me sharig a post means, creating a new post containing the post
    likes = models.ManyToManyField("users.User", verbose_name="Likes", related_name="likes", blank=True)
    location = models.ForeignKey("Location", verbose_name="Location", on_delete=models.CASCADE, null=True, blank=True)
    tags = models.ManyToManyField("Tag", verbose_name="Tags", blank=True)

    @property
    def short_description(self):
        return truncatechars(self.content, 100)

    @property
    def time_ago(self):
        """
            Returns the time since the post was created
        """
        time = datetime.datetime.now() - self.creation_date
        if time.days > 0:
            if time.days > 7:
                return self.creation_date
            return f"{time.days}day ago" if time.days == 1 else f"{time.days}days ago"
        if time.total_seconds() // 3600 > 0:
            return f"{int(time.total_seconds() // 3600)}h ago"
        else:
            return f"{int(time.total_seconds() // 60)}min ago"


class Tag(models.Model):
    name = models.CharField("name", max_length=50)

    @property
    def used_count(self):
        return self.post_set.all().count()

    def __str__(self):
        return self.name


class Location(models.Model):
    name = models.CharField("Location Place Name", max_length=250)
    lat = models.CharField("latitude", max_length=50, null=True, blank=True)
    lng = models.CharField("longitude", max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    """
        A comment is contained in a post, it looks a bit like a post but it doesn't have certain of post features
    """
    author = models.ForeignKey("users.User", verbose_name="Author", on_delete=models.CASCADE)
    content = models.TextField("Text content")
    post = models.ForeignKey("travels.Post", verbose_name="Post", on_delete=models.CASCADE)
    creation_date = models.DateTimeField("creation date", auto_now=False, auto_now_add=True)
    likes = models.ManyToManyField("users.User", verbose_name="Likes", related_name="Commentlikes", blank=True)

    @property
    def time_ago(self):
        """
            Returns the time since the comment was created
        """
        time = datetime.datetime.now() - self.creation_date
        if time.days > 0:
            if time.days > 7:
                return self.creation_date
            return f"{time.days}day" if time.days == 1 else f"{time.days}days"
        if time.total_seconds() // 3600 > 0:
            return f"{int(time.total_seconds() // 3600)}h ago"
        else:
            return f"{int(time.total_seconds() // 60)}min ago"


class PostImage(models.Model):
    """
        PostImages are contained in posts
        Note: It would be great to make a unique name for the images
        so that they don't overwrite another image having the same filename
    """
    post = models.ForeignKey("travels.Post", verbose_name="post", on_delete=models.CASCADE)
    image = models.ImageField("image", upload_to="post/images", height_field=None, width_field=None, max_length=300, blank=True, null=True)


class Album(models.Model):
    """
        An Album contains posts

    """
    user = models.ForeignKey("users.User", verbose_name="User", on_delete=models.CASCADE)
    name = models.CharField("Title", max_length=250)
    posts = models.ManyToManyField("travels.Post", verbose_name="posts")

users/forms.py
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm
from users.models import User
from django.contrib.auth import get_user_model


# Sign Up Form
class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'birthdate',
            'gender',
            'email',
            'password1',
            'password2'
        ]

    def clean(self, admin=False):
        cleaned_data = super().clean()
        if admin:
            return
        try:
            email = cleaned_data.get("email").lower()
            if User.objects.filter(email=email).count() > 0:
                msg = "This email is already in use"
                self.add_error('email', msg)
        except AttributeError:
            # missing attribute means cleaned data returned an error
            pass


class ResetPasswordForm(SetPasswordForm):
    class Meta:
        model = get_user_model()
        fields = ['new_password1', 'new_password2']

users/views.py
from django.shortcuts import render
from django.urls import reverse
from users.forms import RegistrationForm, ResetPasswordForm
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login as Login
from django.contrib import messages
from users.models import User, PasswordForgottenRequest
from django.core.mail import send_mail
import datetime as dt
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from users.decorators import no_user
from django.contrib.auth import logout as django_logout
from travels.models import Tag
import os


# Sign Up View
@no_user
def registration(request):
    """
        This view is used to register a new user
    """
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.set_password(form.cleaned_data['password1'])
            user.email = form.cleaned_data['email'].lower()
            user.save()
            authuser = authenticate(username=user.username, password=form.cleaned_data['password1'])
            if authuser:
                Login(request, authuser)
            return HttpResponseRedirect(reverse("feeds:front_feed"))
        else:
            return render(request, 'registration/registration.html', locals())
    else:
        form = RegistrationForm()
    return render(request, 'registration/registration.html', locals())


@no_user
def forgotpass(request):
    """
        This view is used to send an email to the user to reset his password
    """
    if request.method == "POST":
        email = request.POST["email"].lower().strip()
        user_qs = User.objects.filter(email=email)
        # sets the validity of the link to 24 hours
        validity = dt.datetime.now() + dt.timedelta(hours=24)
        if user_qs.count() > 0:
            passforgot_obj = PasswordForgottenRequest.objects.create(user=user_qs.first(), validity_end=validity)
            # send the email only if not in debug mode
            if not settings.DEBUG:
                send_mail(
                    'Werubin Password Recovery',
                    f"Dear User, we received your request for a password reinitialisation. Please click on this link to reset your password: https://{request.META['HTTP_HOST']}/users/reset-password/{passforgot_obj.link}",
                    settings.EMAIL_HOST_USER,
                    [email],
                    fail_silently=False,
                )
            messages.add_message(
                request, messages.SUCCESS, f"An email has been sent to {email}"
            )
            return HttpResponseRedirect(reverse("users:login"))
        else:
            messages.add_message(
                request, messages.ERROR, f"The email you entered ({email}) doesn't match any user in our database."
            )
    return render(request, 'registration/forgotPass.html', locals())


@no_user
def resetpass(request, key):
    """
        This view is used to reset the password of a user
    """
    passforgot_obj = PasswordForgottenRequest.objects.get(link=key)  # 404 if not found
    # check if the link is still valid
    if dt.datetime.now() > passforgot_obj.validity_end:
        messages.add_message(
            request, messages.ERROR, "Sorry, this link has expired !"
        )
        return HttpResponseRedirect(reverse("users:login"))
    user = passforgot_obj.user
    if request.method == "POST":
        form = ResetPasswordForm(user, request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(
                request, messages.SUCCESS, "Your password has been reset !"
            )
            return HttpResponseRedirect(reverse("users:login"))
        else:
            return render(request, 'registration/resetPass.html', locals())

    form = ResetPasswordForm(user)
    return render(request, 'registration/resetPass.html', locals())


@login_required
def profile(request, username):
    """
        This view is used to display the profile of a user
        but also to edit it
    """
    user = get_object_or_404(User, username=username)
    if request.method == "POST":
        data = request.POST
        if request.user.id == user.id:
            # convert the date to a datetime date object
            birthdate = data['birthdate']
            birthdate_year = birthdate.split("-")[0]
            birthdate_month = birthdate.split("-")[1]
            birthdate_day = birthdate.split("-")[2]
            birthdate_save = dt.date(int(birthdate_year), int(birthdate_month), int(birthdate_day))
            user.birthdate = birthdate_save

            user.gender = data['gender']
            user.first_name = data['first_name']
            user.last_name = data['last_name']
            if request.FILES.get('profile_picture'):
                user.profile_picture = request.FILES.get('profile_picture')
            # keys that contains postTag substring and for which the value is not an empty string
            tag_keys = [key for key in data.keys() if ('userTag' in key and data[key].strip().replace(' ', '') != '')]

            if len(tag_keys) == 0:
                messages.add_message(
                    request, messages.ERROR, "You need to choose at least one tag !"
                )
                return HttpResponseRedirect(reverse("users:profile", args=[username]))

            user.tags.clear()
            # create the tags if they don't exist and add them to the user
            for key in tag_keys:
                tag_name = data[key].strip().replace(' ', '')
                tag, _ = Tag.objects.get_or_create(name=tag_name)
                if tag not in user.tags.all():
                    user.tags.add(tag)
            user.save()
            messages.add_message(
                request, messages.SUCCESS, "Your informations were successfully updated !"
            )
            return HttpResponseRedirect(reverse("users:profile", args=[username]))
        else:
            messages.add_message(
                request, messages.ERROR, "You can not update the information of someone else !"
            )
    followers = User.objects.filter(followers=user)  # user who are following this user
    return render(request, 'userProfile.html', locals())


@login_required
def logout(request):
    """
        This view is used to logout a user
    """
    messages.add_message(
        request, messages.SUCCESS, "You were successfully logged out. We hope to see you soon !"
    )
    django_logout(request)
    return HttpResponseRedirect(reverse("users:login"))


@login_required
def register_tag(request):
    """
        This view is used to add tag for a user
        It is used only if the user has no tag
    """
    if request.method == "POST":
        if len(request.POST.getlist('tag')) == 0:
            messages.add_message(
                request, messages.ERROR, "You need to at least pick one tag"
            )
            return HttpResponseRedirect(reverse("feeds:front_feed"))

        for tag in request.POST.getlist('tag'):
            tag_qs = Tag.objects.filter(name=tag)
            if tag_qs.count() > 0:
                request.user.tags.add(
                    tag_qs.first()
                )
    return HttpResponseRedirect(reverse("feeds:front_feed"))

users/templates/album.html
{% load static %}

<div id="albumContainer" class="album-container" onclick="albumModal({albumId: '{{album.id}}', title: '{{album.name}}', postids: '{% for i in album.posts.all %}{{i.id}} {% endfor %}'})">
    <img class="album-image" width="100%" width="100%" src={% if album.posts.first.postimage_set.count == 0 or album.posts.all.count == 0 %}{% static 'img/default_album.png' %}{% else %}{{album.posts.first.postimage_set.first.image.url}}{% endif %}>
    <div class="check-mark centered"><i class="fa fa-check-circle centered" aria-hidden="true"></i></div>
    <div class="middle">
        <div class="album-name">{{album.name}}</div>
    </div>
</div>

users/templates/editProfileModal.html
{% load static %}

<div class="modal" id="edit-profile-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
              <div class="modal-header">
                <h5 id="edit-profile-modal-title" class="modal-title">"Edit your profile"</h5>
                <button type="button" class="close" onclick="closeEditProfileModal()">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body" id="edit-profile-modal-body">
                <form enctype="multipart/form-data" id="editProfileForm" method="POST" {% if request.user_agent.is_mobile %} style="text-align:left" {% else %}class="ml-5 mr-5" {% endif %}>
                    {% csrf_token %}
                    <div class="col-md-6">
                        <label for="validationCustom02" class="yellow-text form-label">First name</label>
                        <input name="first_name" pattern="[a-zA-Z\s]{1,}" type="text" class="form-control" id="validationCustom02" value='{{user.first_name}}' required>
                    </div>

                    <div class="col-md-6">
                        <label for="validationCustom02" class="yellow-text form-label">Last name</label>
                        <input name="last_name" pattern="[a-zA-Z\s]{1,}" type="text" class="form-control" id="validationCustom02" value='{{user.last_name}}' required>
                    </div>

                    <div class="row">
                        <div class="form-group mb-3 col-12">
                            <label for="pictures" class="form-label yellow-text">Pictures <br> (it will change your current profile picture)</label>
                            <input class="form-control" id="editPictures" type="file" name="profile_picture" accept="image/png, image/jpg, image/gif, image/jpeg">
                        </div>
                    </div>
                    <label for="tagInputs" class="form-label col-2 yellow-text">Tags</label>
                    <div id="addTag" class="center col-1 btn btn-outline-warning" onclick="addNewTagField('user')">
                        +
                    </div>
                    <div id="userTagInputs" class="row col-12 my-2">
                        <div class="row" id="userTag0Row">
                            <div class="form-group col-9">
                                <input class="tagInput center form-control" id="userTag0" type="text" name="userTag" placeholder="Enter a tag...">
                            </div>
                        </div>
                    </div>
                    {%for tag in user.tags.all %}
                    <div id="{{forloop.counter0}}userTagRow" class="row col-12 my-2">
                        <div class="row" id="userTag0Row">
                            <div class="form-group col-9">
                                <input class="tagInput center form-control" id="{{forloop.counter0}}userTag" type="text" name="{{forloop.counter0}}userTag" placeholder="Enter a tag..." value="{{tag.name}}">
                            </div>
                            <div id="deleteTag" class="center ml-1 col-1 btn btn-outline-danger" onclick="deleteTagField({tagRow: '{{forloop.counter0}}userTagRow'})">
                                x
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                    <div class="col-md-6">
                        <label class="yellow-text form-label">Gender</label>
                        <div class="form-check">
                            <input value="F" type="radio" class="form-check-input" id="validationFormCheck1" name="gender" required {%if user.gender == "F"%} checked {%endif%}>
                            <label class="form-check-label yellow-text" for="validationFormCheck1">Female</label>
                        </div>
                        <div class="form-check">
                            <input value="M" type="radio" class="form-check-input" id="validationFormCheck2" name="gender" required {%if user.gender == "M"%} checked {%endif%}>
                            <label class="form-check-label yellow-text" for="validationFormCheck2">Male</label>
                        </div>
                        <div class="form-check mb-3">
                            <input value="O" type="radio" class="form-check-input" id="validationFormCheck3" name="gender" required {%if user.gender == "O"%} checked {%endif%}>
                            <label class="form-check-label yellow-text" for="validationFormCheck3">Other</label>
                            <div class="invalid-feedback">Please select something.</div>
                        </div>
                        <span class="text-danger">{{form.errors.gender}}</span>
                    </div>

                    <div class="col-md-8">
                        <label for="validationCustomDate" class="yellow-text form-label">Birth date</label>
                         <input name="birthdate" type="date" class="form-control" id="validationCustomDate" value='{{user.birthdate_input}}' required>
                    </div>
                    <div class="text-center mt-5">
                        <button class="submit-button btn yellow-bg text-light" type="submit">
                            Publish
                        </button>
                    </div>



                </form>
              </div>
              <div class="modal-footer" id="edit-profile-modal-footer">
              </div>
        </div>
    </div>
</div>

users/templates/userProfile.html
{% extends "navbar.html" %}
{% load static %}
{% block extrahead %}

<!-- CDN -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<link rel="stylesheet" href="{% static 'css/singlePostPage.css' %}">

{% endblock %}
{% block content %}
{%comment %}
TODO Edit Information
{%endcomment%}
<div class="container">
    {%include 'message.html'%}
    <div class="row justify-content-center">
        <div class="col-12 col-md-5">
            <div class="row">
                <div class="my-3 py-3 card">
                    <div class="row" >
                        <div class="col-6">
                            {% if user.profile_picture %}
                                <img class="rounded-image" width=100% src='{{user.profile_picture.url}}'>
                            {% else %}
                                <img class="rounded-image" width=100% src={% static 'img/profile_default.png'%}>
                            {% endif %}
                        </div>
                        <div class="col-6">
                            <h3 class="yellow-darker-text">{{user.username}}</h3>
                            <h6 class="yellow-darker-text">{{user.first_name}} {{user.last_name}}</h6>
                            <p class="yellow-darker-text">
                                Member since
                                <br>
                                {{user.date_joined}}
                                <br>
                                <br>
                                <a class="yellow-link" onclick="openLikeShareModal({ modalType: 'followers', id: '{{user.id}}', username: '{{user.username}}'})" href="javascript:void(0);">{{followers.count}} follower{% if followers.count > 1 %}s{% endif %}</a>
                                <br>
                                <a class="yellow-link" onclick="openLikeShareModal({ modalType: 'following', id: '{{user.id}}', username: '{{user.username}}'})" href="javascript:void(0);">{{user.followers.all.count}} follow{% if user.followers.all.count > 1 %}s{% endif %}</a>
                                <br>
                            </p>
                            {% if user == request.user %}
                            <button class="center btn btn-outline-warning my-2" type="submit" onclick="openEditProfileModal()">Edit profile</button>

                            <a href="{%url 'users:logout'%}"><button class="center btn btn-danger" type="submit">Logout</button></a>
                            {% else %}


                                <button id='followCurrentUserButton'class="center btn btn-outline-warning" onclick="onFollowClick('{{user.id}}', 'followCurrentUserButton')">
                                    {%if user in request.user.followers.all%}
                                        Unfollow
                                    {%else%}
                                        Follow
                                    {%endif%}</button>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="card p-0">
                    <div class="card-header d-block d-md-none border-bottom-0">
                        <h2>
                            <button id="albumButton" class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                                <i id="caret-icon" class="bi bi-caret-down"></i> Albums
                            </button>
                        </h2>
                    </div>

                    <div class="collapse dont-collapse-sm show" id="collapseExample">
                        <div class="card-body">
                            {% if user == request.user%} <button class="center btn btn-outline-warning" onclick="openAlbumModal()">Add album</button>{%endif %}
                            <p class="yellow-darker-text center m-0">
                                {{user.username}}'s Albums

                            </p>

                            <span class="d-flex justify-content-center row">
                                <div class="row">
                                    {% for album in user.album_set.all %}

                                    {% if forloop.counter0|divisibleby:3 %}
                                </div>
                                <div class="row">
                                    {% endif %}
                                    <div class="col-4 p-1">
                                    {% include "album.html" %}
                                    </div>
                                    {% endfor %}
                                </div>
                            </span>
                        </div>
                    </div>
                </div>
            </div>


        </div>

        <div class="col-12 col-md-7">
            <div class="card mt-4 p-1 bg-grey text-center">
                <h1 class="yellow-text">
                    <i class="fa fa-map-signs" aria-hidden="true"></i>
                    Road Map
                    <i class="fa fa-map-signs" aria-hidden="true"></i>
                    </h1>
                <div class="map" id="roadMap"></div>
            </div>

            {% if user == request.user %}
                {% include "posts/postButton.html" %}
                {% include "posts/albumModal.html"%}
                {% include "editProfileModal.html"%}
            {% endif %}
            <div id="posts">
            </div>
            {% include "posts/postModal.html" %}
            {% include "posts/likesSharesModal.html" %}
            {% include "posts/imageModal.html"%}
         </div>
    </div>
</div>


{% endblock %}

{% block extra_js %}
{% include "posts/post.html" %}
<script src="{% static 'js/postModal.js'%}"></script>
<script src="{% static 'js/imageModal.js'%}"></script>
<script src="{% static 'js/albumModal.js'%}"></script>
<script src="{% static 'js/editProfileModal.js'%}"></script>
<script>
    var userId = {{user.id}}
    var noAlbumPictureUrl = "{% static 'img/default_album.png' %}"
</script>
<script src="{% static 'js/userProfile.js'%}"></script>
<script src="{% static 'js/addTagInput.js'%}"></script>
{% endblock %}