feeds/urls.py
from django.urls import path, include
from feeds import views as views


urlpatterns = [
    path("api/", include(('feeds.api_urls', 'feeds_api'), namespace='api')),
    path("feed/<str:tagName>/", views.tag_feed, name='tag_feed'),
    path("", views.front_feed, name='front_feed'),
]

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as dviews
import users.views as views

urlpatterns = [
    path('login/', dviews.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.registration, name='register'),
    path('register_tag/', views.register_tag, name='register_tag'),
    path('forgotpass/', views.forgotpass, name='forgotpass'),
    path('reset-password/<str:key>/', views.resetpass, name='resetpass'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path("api/", include(('users.api_urls', 'users_api'), namespace='api')),

]

werubin/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

# swagger import
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from werubin.generators import BothHttpAndHttpsSchemaGenerator


api_urlpatterns = [
    path('', include(('feeds.urls', 'feeds'), namespace='feeds')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
]
schema_view = get_schema_view(
    openapi.Info(
        title="WERUBIN API Documentation",
        default_version='v1',
        description="🙌 READ ME !!! 🙌 \n In this swagger, you will find all the api endpoint that we provide you. \n\
        This api allows you to interact in any way (except to registering process) with the content of our website \
        in case you want to build an app on top of ours.\
        Note that in order to user the api, you need to be registered on our website. \n \
        We are using Basic Authentication so you can either add the authorization header with your username and password encoded in Base64 separated by a column (:) \
        or if you are using curl, the -u option should work just fine.",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    patterns=api_urlpatterns,
    public=True,
    generator_class=BothHttpAndHttpsSchemaGenerator,
    permission_classes=[permissions.IsAuthenticated],
)
urlpatterns = api_urlpatterns + [

    path('travels/', include(('travels.urls', 'travels'), namespace='travels')),
    path("users/", include(("users.urls", "users"), namespace="users")),
    path('admin/', admin.site.urls),
    # json and yaml version
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    # 2 different UI of swagger
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    # background image in css file
    path('css/users.css', TemplateView.as_view(
        template_name='users.css',
        content_type='text/css')
    ),
    path('js/addToAlbumModal.js', TemplateView.as_view(
        template_name='addToAlbumModal.js',
        content_type='text/javascript')
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # add media url to urlpatterns

werubin/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
        <link rel="stylesheet" href="{% static 'css/main.css'%}?v=1">

        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        {% block extrahead %}
        {% endblock %}
        <title>{{ page_title }}</title>

    </head>

    <body>
        <!-- JQuery -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js" integrity="sha512-57oZ/vW8ANMjR/KQ6Be9v/+/h6bq9/l3f0Oc7vn6qMqyhvPd1cvKBRWWpzu0QoneImqr2SkmO4MSqU+RpHom3Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

        {%block navbar%}
        {%endblock%}
        {% block content %}
        {% endblock %}


        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

        <!-- Bootstrap JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        <script src="{%static 'js/weather.js'%}"></script>

        {% block extra_js %}
        {% endblock %}
    </body>
</html>

werubin/templates/message.html
{% if messages %}
    <div class="container">
        {% for message in messages %}
            <div
                {% if message.tags %}
                    {% if message.tags == "error" %}
                    class="alert alert-danger"
                    {% else %}
                    class="alert alert-{{ message.tags }}"
                    {% endif %}
                {% endif %}
            >
                {{ message |safe }}
            </div>
        {% endfor %}
    </div>
{% endif %}

werubin/templates/navbar.html
{% extends 'base.html' %}

{% load static %}

{% block navbar %}
<nav class="navbar navbar-expand-md navbar-light bg-light p-2">
    <div class="container">
        <div class="row center col-6 col-md-3">
            <a class="werubin-logo row yellow-link center" href="{% url 'feeds:front_feed'%}">
                {%comment%}
                TODO put an svg logo here
                {%endcomment%}
                <p class="col-10 col-md-12 col-lg-10 center m-0 p-0">WERUBIN</p>
                <i class="col-2 col-md-12 col-lg-2 center fa fa-home" aria-hidden="true"></i>
            </a>
        </div>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="row center">
                <div class="navbar-nav center col-12 col-md-3 order-md-2">
                    <a id="profileButton" class="row center yellow-text" href="{% url 'users:profile' request.user.username %}">
                        <i class="center fa fa-user-circle-o fa-2x" aria-hidden="true"></i>
                        <p class="center">Your profile</p>
                    </a>

                </div>

                <div class="center col-12 col-md-9 order-md-1 px-0">
                    <div class="row center mx-1">
                        <div class="col-12 col-md-8 m-2 p-0 autocomplete">
                            <input id="searchBarInput" type="text" placeholder="Enter a tag or a username here...">
                            <input id="searchHidden" type="hidden"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </nav>
  <script src="{% static 'js/searchBar.js' %}"></script>

  {%endblock%}